//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunacod.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lunacod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_122_envelope_empty {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-122-envelope-empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_122_envelope_empty_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-122-envelope-empty@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_122_envelope_empty_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-122-envelope-empty@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_122_envelope_empty_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-122-envelope-empty@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_122_envelope_empty_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-122-envelope-empty@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_122_envelope_empty_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-122-envelope-empty@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_122_envelope_empty_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-122-envelope-empty@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_122_envelope_empty1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-122-envelope-empty1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_122_envelope_empty2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-122-envelope-empty2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_125_envelope_plus {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-125-envelope-plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_125_envelope_plus_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-125-envelope-plus@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_125_envelope_plus_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-125-envelope-plus@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_125_envelope_plus_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-125-envelope-plus@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_125_envelope_plus_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-125-envelope-plus@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_125_envelope_plus_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-125-envelope-plus@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_125_envelope_plus_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-125-envelope-plus@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_125_envelope_plus1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-125-envelope-plus1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_125_envelope_plus2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-125-envelope-plus2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_137_cogwheel {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-137-cogwheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_137_cogwheel_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-137-cogwheel@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_137_cogwheel_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-137-cogwheel@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_137_cogwheel_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-137-cogwheel@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_137_cogwheel_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-137-cogwheel@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_137_cogwheel_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-137-cogwheel@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_137_cogwheel_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-137-cogwheel@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_137_cogwheel1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-137-cogwheel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_137_cogwheel2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-137-cogwheel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_141_database {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-141-database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_141_database_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-141-database@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_141_database_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-141-database@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_141_database_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-141-database@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_141_database_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-141-database@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_141_database_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-141-database@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_141_database_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-141-database@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_141_database1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-141-database1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_141_database2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-141-database2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_44_user_group {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-44-user-group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_44_user_group_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-44-user-group@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_44_user_group_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-44-user-group@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_44_user_group_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-44-user-group@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_44_user_group_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-44-user-group@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_44_user_group_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-44-user-group@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_44_user_group_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-44-user-group@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_44_user_group1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-44-user-group1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_44_user_group2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-44-user-group2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_52_eye {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-52-eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_52_eye_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-52-eye@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_52_eye_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-52-eye@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_52_eye_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-52-eye@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_52_eye_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-52-eye@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_52_eye1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-52-eye1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_52_eye2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-52-eye2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_53_eye_off {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-53-eye-off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_53_eye_off_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-53-eye-off@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_53_eye_off_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-53-eye-off@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_53_eye_off_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-53-eye-off@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_53_eye_off_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-53-eye-off@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_53_eye_off1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-53-eye-off1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_53_eye_off2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-53-eye-off2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close_2x3 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close@2x3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close_3x3 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close@3x3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_599_menu_close2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-599-menu-close2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_713_announcement {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-713-announcement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_713_announcement_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-713-announcement@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_713_announcement_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-713-announcement@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_713_announcement_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-713-announcement@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_713_announcement_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-713-announcement@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_713_announcement_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-713-announcement@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_713_announcement_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-713-announcement@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_713_announcement1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-713-announcement1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_713_announcement2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-713-announcement2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_739_check {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_739_check_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_739_check_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_739_check_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_739_check_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_739_check_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_739_check_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_739_check1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_739_check2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_845_square_question {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-845-square-question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_845_square_question_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-845-square-question@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_845_square_question_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-845-square-question@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_845_square_question_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-845-square-question@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_845_square_question_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-845-square-question@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_845_square_question_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-845-square-question@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_845_square_question_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-845-square-question@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_845_square_question1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-845-square-question1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_845_square_question2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-845-square-question2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_846_square_info {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-846-square-info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_846_square_info_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-846-square-info@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_846_square_info_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-846-square-info@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_846_square_info_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-846-square-info@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_846_square_info_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-846-square-info@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_846_square_info_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-846-square-info@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_846_square_info_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-846-square-info@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_846_square_info1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-846-square-info1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_846_square_info2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-846-square-info2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_847_square_alert {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-847-square-alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_847_square_alert_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-847-square-alert@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_847_square_alert_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-847-square-alert@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_847_square_alert_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-847-square-alert@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_847_square_alert_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-847-square-alert@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_847_square_alert_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-847-square-alert@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_847_square_alert_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-847-square-alert@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_847_square_alert1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-847-square-alert1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_847_square_alert2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-847-square-alert2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_86_reload {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-86-reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_86_reload_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-86-reload@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_86_reload_2x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-86-reload@2x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_86_reload_2x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-86-reload@2x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_86_reload_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-86-reload@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_86_reload_3x1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-86-reload@3x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_86_reload_3x2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-86-reload@3x2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_86_reload1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-86-reload1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glyphicons_basic_86_reload2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-86-reload2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Group_1 {
            get {
                object obj = ResourceManager.GetObject("Group 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Group_11 {
            get {
                object obj = ResourceManager.GetObject("Group 11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pngwing_com {
            get {
                object obj = ResourceManager.GetObject("pngwing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pngwing_com1 {
            get {
                object obj = ResourceManager.GetObject("pngwing.com1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
